import { Router } from 'express';
import multer from 'multer';
import { env } from '../../config/env.js';
import { pool } from '../../database/pool.js';
import { transaction } from '../../database/transaction.js';
import { asyncHandler } from '../../core/async-handler.js';
import { routeParam } from '../../core/route-param.js';
import { created, noContent, ok } from '../../core/http.js';
import { NotFoundError, ValidationError } from '../../core/errors.js';
import { requirePermission } from '../../middleware/permission.js';
import { deleteCloudinaryImage, uploadAnimalImage } from '../../services/cloudinary.service.js';
import { buildInsert } from '../shared/sql.js';
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:env.MAX_IMAGE_MB*1024*1024},fileFilter:(_req,file,cb)=>file.mimetype.startsWith('image/')?cb(null,true):cb(new ValidationError('Solo se permiten imágenes.'))});
export const animalImagesRouter=Router({mergeParams:true});
animalImagesRouter.get('/',requirePermission('IMAGEN_CONSULTAR'),asyncHandler(async(req,res)=>ok(res,(await pool.query('SELECT * FROM animal_imagen WHERE id_animal=$1 AND deleted_at IS NULL ORDER BY es_perfil DESC,orden,created_at',[routeParam(req.params.id, 'id')])).rows)));
animalImagesRouter.post('/',requirePermission('IMAGEN_ADMINISTRAR'),upload.single('imagen'),asyncHandler(async(req,res)=>{if(!req.file)throw new ValidationError('Debes enviar el archivo en el campo imagen.');const exists=await pool.query('SELECT 1 FROM animal WHERE id_animal=$1 AND deleted_at IS NULL',[routeParam(req.params.id, 'id')]);if(!exists.rowCount)throw new NotFoundError('Animal no encontrado.');const cloud=await uploadAnimalImage(req.file.buffer,routeParam(req.params.id, 'id'));const profile=req.body.es_perfil==='true'||req.body.es_perfil===true;const row=await transaction(async c=>{if(profile)await c.query('UPDATE animal_imagen SET es_perfil=FALSE WHERE id_animal=$1 AND deleted_at IS NULL',[routeParam(req.params.id, 'id')]);return (await c.query(buildInsert('animal_imagen',{id_animal:routeParam(req.params.id, 'id'),public_id:cloud.public_id,url:cloud.url,secure_url:cloud.secure_url,formato:cloud.format,ancho:cloud.width,alto:cloud.height,bytes:cloud.bytes,es_perfil:profile,descripcion:req.body.descripcion||null,registrado_por:req.user!.id}))).rows[0];},req.user!.id);return created(res,row);}));
export const imagesRouter=Router();
imagesRouter.patch('/:id/perfil',requirePermission('IMAGEN_ADMINISTRAR'),asyncHandler(async(req,res)=>{const row=await transaction(async c=>{const found=await c.query('SELECT * FROM animal_imagen WHERE id_imagen=$1 AND deleted_at IS NULL FOR UPDATE',[routeParam(req.params.id, 'id')]);if(!found.rows[0])throw new NotFoundError();await c.query('UPDATE animal_imagen SET es_perfil=FALSE WHERE id_animal=$1 AND deleted_at IS NULL',[found.rows[0].id_animal]);return (await c.query('UPDATE animal_imagen SET es_perfil=TRUE WHERE id_imagen=$1 RETURNING *',[routeParam(req.params.id, 'id')])).rows[0];},req.user!.id);return ok(res,row);}));
imagesRouter.patch('/:id',requirePermission('IMAGEN_ADMINISTRAR'),asyncHandler(async(req,res)=>{const row=(await pool.query('UPDATE animal_imagen SET descripcion=COALESCE($2,descripcion),orden=COALESCE($3,orden) WHERE id_imagen=$1 AND deleted_at IS NULL RETURNING *',[routeParam(req.params.id, 'id'),req.body.descripcion,req.body.orden])).rows[0];if(!row)throw new NotFoundError();return ok(res,row);}));
imagesRouter.delete('/:id',requirePermission('IMAGEN_ADMINISTRAR'),asyncHandler(async(req,res)=>{const row=(await pool.query('UPDATE animal_imagen SET deleted_at=NOW(),es_perfil=FALSE WHERE id_imagen=$1 AND deleted_at IS NULL RETURNING public_id',[routeParam(req.params.id, 'id')])).rows[0];if(!row)throw new NotFoundError();await deleteCloudinaryImage(row.public_id);return noContent(res);}));
