import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarRange, Edit3, Milk, Plus, Trash2 } from 'lucide-react';
import { apiRequest, ApiError } from '../../api/client';
import { useAuth } from '../../auth/AuthContext';
import { useToast } from '../../components/ToastContext';
import { Badge, Button, ConfirmDialog, EmptyState, ErrorState, Field, Input, LoadingState, Modal, PageHeader, Select, Textarea } from '../../components/ui';
import type { ActiveLactationCow, DailyProductionSummary, GenericRecord, LactationBirthOption, LactationCowOption, MilkingCowOption, TankProduction } from '../../types/api';
import { currentDateInput, dateInputValue, formatDate, formatNumber, humanizeCode, nullIfEmpty } from '../../utils';

interface LactationForm{id_lactancia?:string;id_vaca:string;id_parto:string;fecha_fin:string;activa:boolean;en_ordeno:boolean;observaciones:string}
interface MilkForm{id_produccion?:string;id_vaca:string;fecha_produccion:string;turno:string;litros:string;observaciones:string}
interface TankForm{id_produccion_tanque?:string;fecha_produccion:string;turno:string;litros:string;observaciones:string}
const emptyLactation=():LactationForm=>({id_vaca:'',id_parto:'',fecha_fin:'',activa:true,en_ordeno:true,observaciones:''});
const emptyMilk=(date=currentDateInput()):MilkForm=>({id_vaca:'',fecha_produccion:date,turno:'UNICO',litros:'',observaciones:''});
const emptyTank=(date=currentDateInput()):TankForm=>({fecha_produccion:date,turno:'UNICO',litros:'',observaciones:''});
const turns=['MANANA','TARDE','NOCHE','UNICO'];

export function ProductionPage(){
  const {hasPermission}=useAuth();const toast=useToast();const client=useQueryClient();
  const [tab,setTab]=useState<'lactations'|'production'|'milking'>('production');const [date,setDate]=useState(currentDateInput());
  const [lactationOpen,setLactationOpen]=useState(false);const [lactation,setLactation]=useState<LactationForm>(emptyLactation);
  const [milkOpen,setMilkOpen]=useState(false);const [milk,setMilk]=useState<MilkForm>(emptyMilk);
  const [tankOpen,setTankOpen]=useState(false);const [tank,setTank]=useState<TankForm>(emptyTank);
  const [deleteItem,setDeleteItem]=useState<{module:string;id:string}|null>(null);
  const lactations=useQuery({queryKey:['records','lactancias'],queryFn:()=>apiRequest<GenericRecord[]>('/registros/lactancias')});
  const productions=useQuery({queryKey:['records','producciones'],queryFn:()=>apiRequest<GenericRecord[]>('/registros/producciones')});
  const tanks=useQuery({queryKey:['production-tanks'],queryFn:()=>apiRequest<TankProduction[]>('/registros/produccion-tanque')});
  const activeCows=useQuery({queryKey:['production-active-cows',milk.fecha_produccion],queryFn:()=>apiRequest<ActiveLactationCow[]>(`/registros/producciones/vacas-activas?fecha=${milk.fecha_produccion}`),enabled:milkOpen&&Boolean(milk.fecha_produccion)});
  const milkingCows=useQuery({queryKey:['production-eligible-cows'],queryFn:()=>apiRequest<MilkingCowOption[]>('/registros/producciones/vacas-elegibles'),enabled:tab==='milking'});
  const summary=useQuery({queryKey:['production-summary',date],queryFn:()=>apiRequest<DailyProductionSummary>(`/registros/producciones/resumen/diario?fecha=${date}`)});
  const females=useQuery({queryKey:['lactations','available-cows',lactation.id_lactancia],queryFn:()=>apiRequest<LactationCowOption[]>(`/registros/lactancias/vacas-disponibles${lactation.id_lactancia?`?id_lactancia=${lactation.id_lactancia}`:''}`),enabled:lactationOpen});
  const births=useQuery({queryKey:['lactations','births',lactation.id_vaca,lactation.id_lactancia],queryFn:()=>apiRequest<LactationBirthOption[]>(`/registros/lactancias/partos?id_vaca=${lactation.id_vaca}${lactation.id_lactancia?`&id_lactancia=${lactation.id_lactancia}`:''}`),enabled:lactationOpen&&Boolean(lactation.id_vaca)});
  const visibleProduction=productions.data?.filter((item)=>dateInputValue(String(item.fecha_produccion))===date)??[];
  const visibleTanks=tanks.data?.filter((item)=>dateInputValue(item.fecha_produccion)===date)??[];
  const refresh=()=>{void client.invalidateQueries({queryKey:['records']});void client.invalidateQueries({queryKey:['production-tanks']});void client.invalidateQueries({queryKey:['production-summary']});void client.invalidateQueries({queryKey:['production-active-cows']});void client.invalidateQueries({queryKey:['production-eligible-cows']});void client.invalidateQueries({queryKey:['dashboard']});};

  const saveLactation=useMutation({mutationFn:()=>{if(!lactation.id_vaca||!lactation.id_parto)throw new Error('Selecciona una vaca y el parto relacionado.');if(!lactation.activa&&!lactation.fecha_fin)throw new Error('Ingresa la fecha de cierre.');return apiRequest(`/registros/lactancias${lactation.id_lactancia?`/${lactation.id_lactancia}`:''}`,{method:lactation.id_lactancia?'PATCH':'POST',body:{id_vaca:lactation.id_vaca,id_parto:lactation.id_parto,fecha_fin:lactation.activa?null:lactation.fecha_fin,activa:lactation.activa,en_ordeno:lactation.activa&&lactation.en_ordeno,observaciones:nullIfEmpty(lactation.observaciones)}});},onSuccess:()=>{toast.show('Lactancia guardada.');setLactationOpen(false);setLactation(emptyLactation());refresh();},onError:(error)=>toast.show(error instanceof ApiError?error.message:(error as Error).message,'error')});
  const saveMilk=useMutation({mutationFn:()=>{if(!milk.id_vaca||!milk.fecha_produccion||!milk.litros)throw new Error('Selecciona una vaca en ordeño, fecha y litros.');return apiRequest(`/registros/producciones${milk.id_produccion?`/${milk.id_produccion}`:''}`,{method:milk.id_produccion?'PATCH':'POST',body:{id_vaca:milk.id_vaca,fecha_produccion:milk.fecha_produccion,turno:milk.turno,litros:Number(milk.litros),observaciones:nullIfEmpty(milk.observaciones),fuente:'MANUAL'}});},onSuccess:()=>{toast.show('Producción por vaca guardada.');setMilkOpen(false);setMilk(emptyMilk(date));refresh();},onError:(error)=>toast.show(error instanceof ApiError?error.message:(error as Error).message,'error')});
  const toggleMilking=useMutation({mutationFn:({id,en_ordeno}:{id:string;en_ordeno:boolean})=>apiRequest(`/registros/producciones/vacas/${id}/ordeno`,{method:'PUT',body:{en_ordeno}}),onSuccess:(_,variables)=>{toast.show(variables.en_ordeno?'Vaca agregada al ordeño.':'Vaca retirada del ordeño.');refresh();},onError:(error)=>toast.show(error instanceof ApiError?error.message:(error as Error).message,'error')});
  const saveTank=useMutation({mutationFn:()=>{if(!tank.fecha_produccion||tank.litros==='')throw new Error('Completa fecha y litros del tanque.');return apiRequest(`/registros/produccion-tanque${tank.id_produccion_tanque?`/${tank.id_produccion_tanque}`:''}`,{method:tank.id_produccion_tanque?'PATCH':'POST',body:{fecha_produccion:tank.fecha_produccion,turno:tank.turno,litros:Number(tank.litros),fuente:'MANUAL',referencia_externa:null,observaciones:nullIfEmpty(tank.observaciones)}});},onSuccess:()=>{toast.show('Total del tanque guardado.');setTankOpen(false);setTank(emptyTank(date));refresh();},onError:(error)=>toast.show(error instanceof ApiError?error.message:(error as Error).message,'error')});
  const remove=useMutation({mutationFn:()=>apiRequest(`/registros/${deleteItem?.module}/${deleteItem?.id}`,{method:'DELETE'}),onSuccess:()=>{toast.show('Registro eliminado.');setDeleteItem(null);refresh();},onError:(error)=>toast.show((error as ApiError).message,'error')});
  const editLactation=(item:GenericRecord)=>{setLactation({id_lactancia:String(item.id_lactancia),id_vaca:String(item.id_vaca),id_parto:String(item.id_parto??''),fecha_fin:dateInputValue(String(item.fecha_fin??'')),activa:Boolean(item.activa),en_ordeno:Boolean(item.en_ordeno),observaciones:String(item.observaciones??'')});setLactationOpen(true);};
  const editMilk=(item:GenericRecord)=>{setMilk({id_produccion:String(item.id_produccion),id_vaca:String(item.id_vaca),fecha_produccion:dateInputValue(String(item.fecha_produccion)),turno:String(item.turno??'UNICO'),litros:String(item.litros??''),observaciones:String(item.observaciones??'')});setMilkOpen(true);};
  const editTank=(item:TankProduction)=>{setTank({id_produccion_tanque:item.id_produccion_tanque,fecha_produccion:dateInputValue(item.fecha_produccion),turno:item.turno,litros:String(item.litros),observaciones:item.observaciones??''});setTankOpen(true);};

  const headerAction=tab==='lactations'&&hasPermission('LACTANCIA_ADMINISTRAR')?<Button onClick={()=>{setLactation(emptyLactation());setLactationOpen(true);}}><Plus size={18}/>Nueva lactancia</Button>:tab==='production'&&hasPermission('PRODUCCION_ADMINISTRAR')?<div className="header-actions"><Button variant="secondary" onClick={()=>{setTank(emptyTank(date));setTankOpen(true);}}><Milk size={18}/>Total del tanque</Button><Button onClick={()=>{setMilk(emptyMilk(date));setMilkOpen(true);}}><Plus size={18}/>Producción por vaca</Button></div>:undefined;

  return <div><PageHeader title="Producción de leche" description="Controla lactancias, vacas en ordeño, producción por vaca y medición total del tanque." action={headerAction}/><div className="page-tabs"><button className={tab==='production'?'active':''} onClick={()=>setTab('production')}><Milk size={17}/>Producción diaria</button><button className={tab==='lactations'?'active':''} onClick={()=>setTab('lactations')}><CalendarRange size={17}/>Lactancias</button><button className={tab==='milking'?'active':''} onClick={()=>setTab('milking')}><Milk size={17}/>En ordeño</button></div>
  {tab==='production'?<ProductionDaily date={date} setDate={setDate} summary={summary.data} loading={productions.isLoading} error={productions.error as Error|null} retry={()=>void productions.refetch()} rows={visibleProduction} tanks={visibleTanks} canEdit={hasPermission('PRODUCCION_ADMINISTRAR')} editMilk={editMilk} editTank={editTank} remove={setDeleteItem}/>:tab==='milking'?<MilkingCows rows={milkingCows.data??[]} loading={milkingCows.isLoading} error={milkingCows.error as Error|null} retry={()=>void milkingCows.refetch()} canEdit={hasPermission('PRODUCCION_ADMINISTRAR')} saving={toggleMilking.isPending} toggle={(cow)=>toggleMilking.mutate({id:cow.id_animal,en_ordeno:!cow.en_ordeno})}/>:lactations.isLoading?<LoadingState/>:lactations.isError?<ErrorState message={(lactations.error as Error).message} onRetry={()=>void lactations.refetch()}/>:lactations.data?.length?<div className="table-card"><div className="table-responsive"><table className="data-table"><thead><tr><th>Vaca</th><th>Inicio</th><th>Fin</th><th>Estado</th><th>En ordeño</th><th>Parto</th><th>Observaciones</th>{hasPermission('LACTANCIA_ADMINISTRAR')?<th>Acciones</th>:null}</tr></thead><tbody>{lactations.data.map((item)=><tr key={String(item.id_lactancia)}><td><strong>{String(item.animal)}</strong><small>{item.codigo_arete?`Arete ${item.codigo_arete}`:''}</small></td><td>{formatDate(String(item.fecha_inicio))}</td><td>{formatDate(item.fecha_fin?String(item.fecha_fin):null)}</td><td><Badge tone={item.activa?'success':'neutral'}>{item.activa?'Activa':'Cerrada'}</Badge></td><td><Badge tone={item.en_ordeno?'info':'neutral'}>{item.en_ordeno?'Sí':'No'}</Badge></td><td>{item.id_parto?'Relacionado':'—'}</td><td>{String(item.observaciones??'—')}</td>{hasPermission('LACTANCIA_ADMINISTRAR')?<td><div className="inline-actions"><Button variant="ghost" onClick={()=>editLactation(item)}><Edit3 size={16}/></Button><Button variant="ghost" onClick={()=>setDeleteItem({module:'lactancias',id:String(item.id_lactancia)})}><Trash2 size={16}/></Button></div></td>:null}</tr>)}</tbody></table></div></div>:<EmptyState icon={CalendarRange} title="Sin lactancias" description="Registra una lactancia vinculada con un parto."/>}
  {lactationOpen?<LactationModal form={lactation} setForm={setLactation} females={females.data??[]} births={births.data??[]} cowsLoading={females.isLoading} birthsLoading={births.isLoading} close={()=>setLactationOpen(false)} save={()=>saveLactation.mutate()} loading={saveLactation.isPending}/>:null}
  {milkOpen?<Modal title={milk.id_produccion?'Editar producción':'Producción por vaca'} onClose={()=>setMilkOpen(false)} footer={<><Button variant="ghost" onClick={()=>setMilkOpen(false)}>Cancelar</Button><Button onClick={()=>saveMilk.mutate()} loading={saveMilk.isPending}>Guardar</Button></>}><div className="form-stack"><Field label="Fecha" required><Input type="date" value={milk.fecha_produccion} onChange={(event)=>setMilk({...milk,fecha_produccion:event.target.value,id_vaca:''})}/></Field><Field label="Vaca en ordeño" required hint="Solo aparecen vacas marcadas en ordeño y con un parto dentro de los 18 meses anteriores; la lactancia activa es opcional."><Select value={milk.id_vaca} onChange={(event)=>setMilk({...milk,id_vaca:event.target.value})}><option value="">Selecciona</option>{activeCows.data?.map((cow)=><option key={cow.id_animal} value={cow.id_animal}>{cow.nombre}{cow.codigo_arete?` · ${cow.codigo_arete}`:''}</option>)}</Select></Field><Field label="Turno"><Select value={milk.turno} onChange={(event)=>setMilk({...milk,turno:event.target.value})}>{turns.map((turn)=><option key={turn} value={turn}>{humanizeCode(turn)}</option>)}</Select></Field><Field label="Litros" required><Input type="number" min="0" step="0.001" value={milk.litros} onChange={(event)=>setMilk({...milk,litros:event.target.value})}/></Field><Field label="Observaciones"><Textarea value={milk.observaciones} onChange={(event)=>setMilk({...milk,observaciones:event.target.value})}/></Field></div></Modal>:null}
  {tankOpen?<Modal title={tank.id_produccion_tanque?'Editar medición del tanque':'Total en tanque'} onClose={()=>setTankOpen(false)} footer={<><Button variant="ghost" onClick={()=>setTankOpen(false)}>Cancelar</Button><Button onClick={()=>saveTank.mutate()} loading={saveTank.isPending}>Guardar</Button></>}><div className="form-stack"><Field label="Fecha" required><Input type="date" value={tank.fecha_produccion} onChange={(event)=>setTank({...tank,fecha_produccion:event.target.value})}/></Field><Field label="Turno"><Select value={tank.turno} onChange={(event)=>setTank({...tank,turno:event.target.value})}>{turns.map((turn)=><option key={turn} value={turn}>{humanizeCode(turn)}</option>)}</Select></Field><Field label="Litros en tanque" required><Input type="number" min="0" step="0.001" value={tank.litros} onChange={(event)=>setTank({...tank,litros:event.target.value})}/></Field><Field label="Observaciones"><Textarea value={tank.observaciones} onChange={(event)=>setTank({...tank,observaciones:event.target.value})}/></Field></div></Modal>:null}
  {deleteItem?<ConfirmDialog title="Eliminar registro" message="El registro dejará de contabilizarse en los totales." onClose={()=>setDeleteItem(null)} onConfirm={()=>remove.mutate()} loading={remove.isPending}/>:null}</div>;
}

function ProductionDaily({date,setDate,summary,loading,error,retry,rows,tanks,canEdit,editMilk,editTank,remove}:{date:string;setDate:(value:string)=>void;summary?:DailyProductionSummary;loading:boolean;error:Error|null;retry:()=>void;rows:GenericRecord[];tanks:TankProduction[];canEdit:boolean;editMilk:(item:GenericRecord)=>void;editTank:(item:TankProduction)=>void;remove:(item:{module:string;id:string})=>void}){
  return <><div className="toolbar"><Field label="Fecha de producción"><Input type="date" value={date} onChange={(event)=>setDate(event.target.value)}/></Field></div><div className="summary-cards production-summary"><div><small>Total por vacas</small><strong>{formatNumber(summary?.total_vacas??0,3)} L</strong><span>{summary?.vacas_registradas??0} vacas</span></div><div><small>Total en tanque</small><strong>{formatNumber(summary?.total_tanque??0,3)} L</strong><span>Medición independiente</span></div><div><small>Diferencia tanque − vacas</small><strong>{formatNumber(summary?.diferencia??0,3)} L</strong><span>Control del margen</span></div></div>{loading?<LoadingState/>:error?<ErrorState message={error.message} onRetry={retry}/>:<><section><h2>Producción por vaca</h2>{rows.length?<div className="table-card"><div className="table-responsive"><table className="data-table"><thead><tr><th>Vaca</th><th>Turno</th><th>Litros</th><th>Fuente</th>{canEdit?<th>Acciones</th>:null}</tr></thead><tbody>{rows.map((item)=><tr key={String(item.id_produccion)}><td><strong>{String(item.animal)}</strong><small>{item.codigo_arete?`Arete ${item.codigo_arete}`:''}</small></td><td>{humanizeCode(String(item.turno))}</td><td><strong>{formatNumber(item.litros as number|string,3)} L</strong></td><td><Badge tone={item.fuente==='SENSOR'?'info':'neutral'}>{humanizeCode(String(item.fuente??'MANUAL'))}</Badge></td>{canEdit?<td><div className="inline-actions"><Button variant="ghost" onClick={()=>editMilk(item)}><Edit3 size={16}/></Button><Button variant="ghost" onClick={()=>remove({module:'producciones',id:String(item.id_produccion)})}><Trash2 size={16}/></Button></div></td>:null}</tr>)}</tbody></table></div></div>:<EmptyState icon={Milk} title="Sin producción por vaca" description="Agrega una vaca a En ordeño para registrar su producción diaria."/>}</section><section><h2>Medición del tanque</h2>{tanks.length?<div className="table-card"><div className="table-responsive"><table className="data-table"><thead><tr><th>Turno</th><th>Litros</th><th>Fuente</th><th>Observaciones</th>{canEdit?<th>Acciones</th>:null}</tr></thead><tbody>{tanks.map((item)=><tr key={item.id_produccion_tanque}><td>{humanizeCode(item.turno)}</td><td><strong>{formatNumber(item.litros,3)} L</strong></td><td><Badge tone={item.fuente==='SENSOR'?'info':'neutral'}>{humanizeCode(item.fuente)}</Badge></td><td>{item.observaciones||'—'}</td>{canEdit?<td><div className="inline-actions"><Button variant="ghost" onClick={()=>editTank(item)}><Edit3 size={16}/></Button><Button variant="ghost" onClick={()=>remove({module:'produccion-tanque',id:item.id_produccion_tanque})}><Trash2 size={16}/></Button></div></td>:null}</tr>)}</tbody></table></div></div>:<EmptyState icon={Milk} title="Sin medición de tanque" description="Registra el volumen total para compararlo con la suma por vaca."/>}</section></>}</>;
}

function MilkingCows({rows,loading,error,retry,canEdit,saving,toggle}:{rows:MilkingCowOption[];loading:boolean;error:Error|null;retry:()=>void;canEdit:boolean;saving:boolean;toggle:(cow:MilkingCowOption)=>void}){
  if(loading)return <LoadingState/>;
  if(error)return <ErrorState message={error.message} onRetry={retry}/>;
  if(!rows.length)return <EmptyState icon={Milk} title="Sin vacas elegibles" description="Para entrar en ordeño, la vaca debe tener un parto registrado dentro de los últimos 18 meses."/>;
  return <div className="table-card"><div className="table-responsive"><table className="data-table"><thead><tr><th>Vaca</th><th>Último parto</th><th>Lactancia activa</th><th>Estado</th>{canEdit?<th>Acción</th>:null}</tr></thead><tbody>{rows.map((cow)=><tr key={cow.id_animal}><td><strong>{cow.nombre}</strong><small>{cow.codigo_arete?`Arete ${cow.codigo_arete}`:'Sin arete'}</small></td><td>{formatDate(cow.fecha_parto)}</td><td>{cow.lactancia_activa?<Badge tone="info">Sí</Badge>:<Badge tone="neutral">No requerida</Badge>}</td><td><Badge tone={cow.en_ordeno?'success':'neutral'}>{cow.en_ordeno?'En ordeño':'Fuera de ordeño'}</Badge></td>{canEdit?<td><Button variant={cow.en_ordeno?'ghost':'primary'} disabled={saving} onClick={()=>toggle(cow)}>{cow.en_ordeno?'Retirar':'Agregar'}</Button></td>:null}</tr>)}</tbody></table></div></div>;
}

function LactationModal({form,setForm,females,births,cowsLoading,birthsLoading,close,save,loading}:{form:LactationForm;setForm:(form:LactationForm)=>void;females:LactationCowOption[];births:LactationBirthOption[];cowsLoading:boolean;birthsLoading:boolean;close:()=>void;save:()=>void;loading:boolean}){
  const availableBirths=births.filter((birth)=>!birth.ya_relacionado||birth.id_parto===form.id_parto);
  const selectedBirth=births.find((item)=>item.id_parto===form.id_parto);
  return <Modal title={form.id_lactancia?'Editar lactancia':'Nueva lactancia'} onClose={close} footer={<><Button variant="ghost" onClick={close}>Cancelar</Button><Button onClick={save} loading={loading}>Guardar</Button></>}><div className="form-stack"><Field label="Vaca con parto registrado" required><Select value={form.id_vaca} disabled={cowsLoading} onChange={(event)=>setForm({...form,id_vaca:event.target.value,id_parto:''})}><option value="">{cowsLoading?'Cargando vacas…':'Selecciona'}</option>{females.map((animal)=><option key={animal.id_animal} value={animal.id_animal}>{animal.nombre}{animal.codigo_arete?` · ${animal.codigo_arete}`:''}</option>)}</Select>{!cowsLoading&&!females.length?<small className="muted">No hay vacas con parto registrado que estén libres de otra lactancia activa.</small>:null}</Field><Field label="Parto relacionado" required hint="La lactancia comenzará automáticamente en la fecha de este parto."><Select value={form.id_parto} disabled={!form.id_vaca||birthsLoading} onChange={(event)=>setForm({...form,id_parto:event.target.value})}><option value="">{!form.id_vaca?'Selecciona primero una vaca':birthsLoading?'Cargando partos…':'Selecciona un parto'}</option>{availableBirths.map((birth)=><option key={birth.id_parto} value={birth.id_parto}>{formatDate(birth.fecha_parto)} · {birth.total_crias} cría(s)</option>)}</Select>{form.id_vaca&&!birthsLoading&&!availableBirths.length?<small className="muted">Esta vaca no tiene partos disponibles para relacionar.</small>:null}</Field>{selectedBirth?<div className="form-alert"><strong>Inicio automático:</strong> {formatDate(selectedBirth.fecha_parto)}</div>:null}<label className="checkbox"><input type="checkbox" checked={form.activa} onChange={(event)=>setForm({...form,activa:event.target.checked,en_ordeno:event.target.checked?form.en_ordeno:false,fecha_fin:event.target.checked?'':form.fecha_fin})}/>Lactancia activa</label>{form.activa?<label className="checkbox"><input type="checkbox" checked={form.en_ordeno} onChange={(event)=>setForm({...form,en_ordeno:event.target.checked})}/>En ordeño</label>:<Field label="Fin" required><Input type="date" min={selectedBirth?dateInputValue(selectedBirth.fecha_parto):undefined} value={form.fecha_fin} onChange={(event)=>setForm({...form,fecha_fin:event.target.value})}/></Field>}<small className="muted">Solo las vacas marcadas “En ordeño” estarán disponibles al registrar producción diaria.</small><Field label="Observaciones"><Textarea value={form.observaciones} onChange={(event)=>setForm({...form,observaciones:event.target.value})}/></Field></div></Modal>;
}
