import { useEffect, useMemo, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CalendarRange, Edit3, Gauge, Milk, Plus, SlidersHorizontal, Trash2 } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { apiRequest, ApiError } from '../../api/client';
import { useAuth } from '../../auth/AuthContext';
import { useToast } from '../../components/ToastContext';
import { AnimalIdentity, AnimalSelect, useAnimalDirectory } from '../../components/AnimalPicker';
import { Badge, Button, Card, CompactToolbar, ConfirmDialog, EmptyState, ErrorState, Field, FloatingActionDock, IconButton, Input, LoadingState, Modal, Select, Textarea } from '../../components/ui';
import type { ActiveLactationCow, GenericRecord, LactationBirthOption, LactationCowOption, TankProduction } from '../../types/api';
import { currentDateInput, dateInputValue, formatDate, formatNumber, humanizeCode, nullIfEmpty } from '../../utils';
import { ProductionAnimalFilter, ProductionChart, type ProductionChartSeries } from './ProductionChart';

interface LactationForm{id_lactancia?:string;id_vaca:string;id_parto:string;fecha_fin:string;activa:boolean;en_ordeno:boolean;observaciones:string}
interface MilkForm{id_produccion?:string;id_vaca:string;fecha_produccion:string;turno:string;litros:string;observaciones:string}
interface TankForm{id_produccion_tanque?:string;fecha_produccion:string;turno:string;litros:string;observaciones:string}
interface AnimalProductionGroup{id:string;label:string;start:string;rows:GenericRecord[];total:number}
const emptyLactation=():LactationForm=>({id_vaca:'',id_parto:'',fecha_fin:'',activa:true,en_ordeno:true,observaciones:''});
const emptyMilk=(date=currentDateInput()):MilkForm=>({id_vaca:'',fecha_produccion:date,turno:'UNICO',litros:'',observaciones:''});
const emptyTank=(date=currentDateInput()):TankForm=>({fecha_produccion:date,turno:'UNICO',litros:'',observaciones:''});
const turns=['MANANA','TARDE','NOCHE','UNICO'];

export function ProductionPage(){
  const {hasPermission}=useAuth();const toast=useToast();const client=useQueryClient();
  const navigate=useNavigate();
  const [searchParams,setSearchParams]=useSearchParams();
  const [tab,setTab]=useState<'lactations'|'production'>(searchParams.get('tab')==='lactations'?'lactations':'production');const [date,setDate]=useState(searchParams.get('fecha')??currentDateInput());
  const [query,setQuery]=useState('');const [filtersOpen,setFiltersOpen]=useState(Boolean(searchParams.get('animal')));const [animalFilter,setAnimalFilter]=useState(searchParams.get('animal')??'');const [fromDate,setFromDate]=useState('');const [toDate,setToDate]=useState('');
  const [lactationOpen,setLactationOpen]=useState(false);const [lactation,setLactation]=useState<LactationForm>(emptyLactation);
  const [milkOpen,setMilkOpen]=useState(false);const [milk,setMilk]=useState<MilkForm>(emptyMilk);
  const [tankOpen,setTankOpen]=useState(false);const [tank,setTank]=useState<TankForm>(emptyTank);
  const consumedAction=useRef(false);
  const [deleteItem,setDeleteItem]=useState<{module:string;id:string}|null>(null);
  const lactations=useQuery({queryKey:['records','lactancias'],queryFn:()=>apiRequest<GenericRecord[]>('/registros/lactancias')});
  const productions=useQuery({queryKey:['records','producciones'],queryFn:()=>apiRequest<GenericRecord[]>('/registros/producciones')});
  const tanks=useQuery({queryKey:['production-tanks'],queryFn:()=>apiRequest<TankProduction[]>('/registros/produccion-tanque')});
  const activeCows=useQuery({queryKey:['production-active-cows',milk.fecha_produccion,milk.turno,milk.id_produccion],queryFn:()=>{const query=new URLSearchParams({fecha:milk.fecha_produccion,turno:milk.turno});if(milk.id_produccion)query.set('excluir_id',milk.id_produccion);return apiRequest<ActiveLactationCow[]>(`/registros/producciones/vacas-activas?${query}`);},enabled:milkOpen&&Boolean(milk.fecha_produccion)&&Boolean(milk.turno),staleTime:60_000,retry:1});
  const females=useQuery({queryKey:['lactations','available-cows',lactation.id_lactancia],queryFn:()=>apiRequest<LactationCowOption[]>(`/registros/lactancias/vacas-disponibles${lactation.id_lactancia?`?id_lactancia=${lactation.id_lactancia}`:''}`),enabled:lactationOpen});
  const births=useQuery({queryKey:['lactations','births',lactation.id_vaca,lactation.id_lactancia],queryFn:()=>apiRequest<LactationBirthOption[]>(`/registros/lactancias/partos?id_vaca=${lactation.id_vaca}${lactation.id_lactancia?`&id_lactancia=${lactation.id_lactancia}`:''}`),enabled:lactationOpen&&Boolean(lactation.id_vaca)});
  const directory=useAnimalDirectory();
  const cachedActiveCows=useMemo<ActiveLactationCow[]>(()=>{
    if(!milk.fecha_produccion)return[];
    const registered=new Set((productions.data??[]).filter((item)=>String(item.id_produccion)!==milk.id_produccion&&dateInputValue(String(item.fecha_produccion??''))===milk.fecha_produccion&&String(item.turno??'UNICO')===milk.turno).map((item)=>String(item.id_vaca)));
    return (lactations.data??[]).filter((item)=>Boolean(item.activa)&&Boolean(item.en_ordeno)&&dateInputValue(String(item.fecha_inicio??''))<=milk.fecha_produccion&&(!item.fecha_fin||dateInputValue(String(item.fecha_fin))>=milk.fecha_produccion)&&!registered.has(String(item.id_vaca))).map((item)=>({
      id_animal:String(item.id_vaca),nombre:String(item.animal??item.vaca??directory.byId.get(String(item.id_vaca))?.nombre??'Animal'),codigo_arete:item.codigo_arete?String(item.codigo_arete):directory.byId.get(String(item.id_vaca))?.codigo_arete??null,id_lactancia:String(item.id_lactancia),fecha_inicio:String(item.fecha_inicio),
    }));
  },[directory.byId,lactations.data,milk.fecha_produccion,milk.id_produccion,milk.turno,productions.data]);
  const selectableCows=activeCows.data??cachedActiveCows;
  const visibleProduction=productions.data?.filter((item)=>dateInputValue(String(item.fecha_produccion))===date)??[];
  const visibleTanks=tanks.data?.filter((item)=>dateInputValue(item.fecha_produccion)===date)??[];
  const animalOptions=useMemo(()=>{const map=new Map<string,string>();for(const item of productions.data??[]){const id=String(item.id_vaca??'');if(id)map.set(id,String(item.animal??item.nombre??'Animal'));}return [...map.entries()].sort((a,b)=>a[1].localeCompare(b[1]));},[productions.data]);
  const chartRows=useMemo(()=>(productions.data??[]).filter((item)=>{const animal=String(item.animal??item.nombre??'').toLowerCase();const itemDate=dateInputValue(String(item.fecha_produccion??''));return(!animalFilter||String(item.id_vaca)===animalFilter)&&(!query||animal.includes(query.toLowerCase()))&&(!fromDate||itemDate>=fromDate)&&(!toDate||itemDate<=toDate);}),[productions.data,animalFilter,query,fromDate,toDate]);
  const chartTankRows=useMemo(()=>(tanks.data??[]).filter((item)=>{const itemDate=dateInputValue(item.fecha_produccion);return(!fromDate||itemDate>=fromDate)&&(!toDate||itemDate<=toDate);}),[tanks.data,fromDate,toDate]);
  const tankByDate=useMemo(()=>chartTankRows.reduce<Record<string,number>>((result,item)=>{const key=dateInputValue(item.fecha_produccion);result[key]=(result[key]??0)+Number(item.litros??0);return result;},{}),[chartTankRows]);
  const animalProductionGroups=useMemo<AnimalProductionGroup[]>(()=>{
    if(!animalFilter)return[];
    const rows=chartRows.filter((item)=>String(item.id_vaca)===animalFilter);
    const related=(lactations.data??[]).filter((item)=>String(item.id_vaca)===animalFilter).sort((a,b)=>Date.parse(String(a.fecha_inicio))-Date.parse(String(b.fecha_inicio)));
    const buckets=new Map<string,GenericRecord[]>();
    for(const row of rows){
      const rowDate=dateInputValue(String(row.fecha_produccion));
      const match=row.id_lactancia?related.find((item)=>String(item.id_lactancia)===String(row.id_lactancia)):[...related].reverse().find((item)=>{const start=dateInputValue(String(item.fecha_inicio));const end=item.fecha_fin?dateInputValue(String(item.fecha_fin)):'';return rowDate>=start&&(!end||rowDate<=end);});
      const key=match?String(match.id_lactancia):'unlinked';
      buckets.set(key,[...(buckets.get(key)??[]),row]);
    }
    const result=related.map((item)=>{const groupRows=(buckets.get(String(item.id_lactancia))??[]).sort((a,b)=>Date.parse(String(b.fecha_produccion))-Date.parse(String(a.fecha_produccion)));const birthDate=dateInputValue(String(item.fecha_parto??item.fecha_inicio));return{id:String(item.id_lactancia),label:`Parto ${formatDate(birthDate)}`,start:dateInputValue(String(item.fecha_inicio)),rows:groupRows,total:groupRows.reduce((sum,row)=>sum+Number(row.litros??0),0)};}).filter((item)=>item.rows.length);
    const unlinked=(buckets.get('unlinked')??[]).sort((a,b)=>Date.parse(String(b.fecha_produccion))-Date.parse(String(a.fecha_produccion)));
    if(unlinked.length){const start=[...unlinked].sort((a,b)=>Date.parse(String(a.fecha_produccion))-Date.parse(String(b.fecha_produccion)))[0];result.push({id:'unlinked',label:'Sin parto relacionado',start:dateInputValue(String(start.fecha_produccion)),rows:unlinked,total:unlinked.reduce((sum,row)=>sum+Number(row.litros??0),0)});}
    return result;
  },[animalFilter,chartRows,lactations.data]);
  const chartSeries=useMemo<ProductionChartSeries[]>(()=>{
    const aggregate=(id:string,label:string,rows:GenericRecord[],xFor:(item:GenericRecord)=>number,detailFor:(item:GenericRecord)=>string)=>{const points=new Map<number,{y:number;date:string;detail:string}>();for(const item of rows){const x=xFor(item);if(!Number.isFinite(x))continue;const previous=points.get(x);points.set(x,{y:(previous?.y??0)+Number(item.litros??0),date:String(item.fecha_produccion??''),detail:detailFor(item)});}return{id,label,points:[...points.entries()].sort((a,b)=>a[0]-b[0]).map(([x,point])=>({x,...point}))};};
    if(animalFilter)return animalProductionGroups.map((group)=>aggregate(group.id,group.label,group.rows,(item)=>Math.max(0,Math.round((Date.parse(dateInputValue(String(item.fecha_produccion)))-Date.parse(group.start))/86400000)),(item)=>`Día ${Math.max(0,Math.round((Date.parse(dateInputValue(String(item.fecha_produccion)))-Date.parse(group.start))/86400000))} · ${formatDate(String(item.fecha_produccion))}`)).filter((item)=>item.points.length);
    const grouped=new Map<string,GenericRecord[]>();for(const item of chartRows){const id=String(item.id_vaca??'sin-id');grouped.set(id,[...(grouped.get(id)??[]),item]);}return [...grouped.entries()].map(([id,rows])=>aggregate(id,String(rows[0]?.animal??rows[0]?.nombre??'Animal'),rows,(item)=>Date.parse(dateInputValue(String(item.fecha_produccion))),item=>formatDate(String(item.fecha_produccion)))).filter((item)=>item.points.length);
  },[animalFilter,animalProductionGroups,chartRows]);
  const detailProduction=(productions.data??[]).find((item)=>String(item.id_produccion)===searchParams.get('registro'));
  const detailTank=(tanks.data??[]).find((item)=>item.id_produccion_tanque===searchParams.get('tanque'));
  const detailLactation=(lactations.data??[]).find((item)=>String(item.id_lactancia)===searchParams.get('lactancia'));
  const closeDetailParam=(key:string)=>{const next=new URLSearchParams(searchParams);next.delete(key);setSearchParams(next);};
  const refresh=()=>{void client.invalidateQueries({queryKey:['records']});void client.invalidateQueries({queryKey:['production-tanks']});void client.invalidateQueries({queryKey:['production-summary']});void client.invalidateQueries({queryKey:['production-active-cows']});void client.invalidateQueries({queryKey:['dashboard']});};

  const saveLactation=useMutation({mutationFn:()=>{if(!lactation.id_vaca||!lactation.id_parto)throw new Error('Selecciona una vaca y el parto relacionado.');if(!lactation.activa&&!lactation.fecha_fin)throw new Error('Ingresa la fecha de cierre.');return apiRequest(`/registros/lactancias${lactation.id_lactancia?`/${lactation.id_lactancia}`:''}`,{method:lactation.id_lactancia?'PATCH':'POST',body:{id_vaca:lactation.id_vaca,id_parto:lactation.id_parto,fecha_fin:lactation.activa?null:lactation.fecha_fin,activa:lactation.activa,en_ordeno:lactation.activa&&lactation.en_ordeno,observaciones:nullIfEmpty(lactation.observaciones)}});},onSuccess:()=>{toast.show('Lactancia guardada.');setLactationOpen(false);setLactation(emptyLactation());refresh();},onError:(error)=>toast.show(error instanceof ApiError?error.message:(error as Error).message,'error')});
  const saveMilk=useMutation({mutationFn:()=>{if(!milk.id_vaca||!milk.fecha_produccion||!milk.litros)throw new Error('Selecciona una vaca con lactancia activa, fecha y litros.');return apiRequest(`/registros/producciones${milk.id_produccion?`/${milk.id_produccion}`:''}`,{method:milk.id_produccion?'PATCH':'POST',body:{id_vaca:milk.id_vaca,fecha_produccion:milk.fecha_produccion,turno:milk.turno,litros:Number(milk.litros),observaciones:nullIfEmpty(milk.observaciones),fuente:'MANUAL'}});},onSuccess:()=>{toast.show('Producción por vaca guardada.');setMilkOpen(false);setMilk(emptyMilk(date));refresh();},onError:(error)=>toast.show(error instanceof ApiError?error.message:(error as Error).message,'error')});
  const saveTank=useMutation({mutationFn:()=>{if(!tank.fecha_produccion||tank.litros==='')throw new Error('Completa fecha y litros del tanque.');return apiRequest(`/registros/produccion-tanque${tank.id_produccion_tanque?`/${tank.id_produccion_tanque}`:''}`,{method:tank.id_produccion_tanque?'PATCH':'POST',body:{fecha_produccion:tank.fecha_produccion,turno:tank.turno,litros:Number(tank.litros),fuente:'MANUAL',referencia_externa:null,observaciones:nullIfEmpty(tank.observaciones)}});},onSuccess:()=>{toast.show('Total del tanque guardado.');setTankOpen(false);setTank(emptyTank(date));refresh();},onError:(error)=>toast.show(error instanceof ApiError?error.message:(error as Error).message,'error')});
  const remove=useMutation({mutationFn:()=>apiRequest(`/registros/${deleteItem?.module}/${deleteItem?.id}`,{method:'DELETE'}),onSuccess:()=>{toast.show('Registro eliminado.');setDeleteItem(null);refresh();},onError:(error)=>toast.show((error as ApiError).message,'error')});
  const editLactation=(item:GenericRecord)=>{setLactation({id_lactancia:String(item.id_lactancia),id_vaca:String(item.id_vaca),id_parto:String(item.id_parto??''),fecha_fin:dateInputValue(String(item.fecha_fin??'')),activa:Boolean(item.activa),en_ordeno:Boolean(item.en_ordeno),observaciones:String(item.observaciones??'')});setLactationOpen(true);};
  const editMilk=(item:GenericRecord)=>{setMilk({id_produccion:String(item.id_produccion),id_vaca:String(item.id_vaca),fecha_produccion:dateInputValue(String(item.fecha_produccion)),turno:String(item.turno??'UNICO'),litros:String(item.litros??''),observaciones:String(item.observaciones??'')});setMilkOpen(true);};
  const editTank=(item:TankProduction)=>{setTank({id_produccion_tanque:item.id_produccion_tanque,fecha_produccion:dateInputValue(item.fecha_produccion),turno:item.turno,litros:String(item.litros),observaciones:item.observaciones??''});setTankOpen(true);};
  useEffect(()=>{if(consumedAction.current||searchParams.get('nuevo')!=='1')return;consumedAction.current=true;const animalId=searchParams.get('animal')??'';setTab('production');setMilk({...emptyMilk(date),id_vaca:animalId});setMilkOpen(true);},[date,searchParams]);

  return <div className="module-no-header"><CompactToolbar search={query} onSearch={setQuery} placeholder="Buscar animal…" count={tab==='production'?chartRows.length:lactations.data?.length??0} actions={<IconButton className={filtersOpen?'active':''} label="Filtros avanzados" onClick={()=>setFiltersOpen((value)=>!value)}><SlidersHorizontal size={18}/></IconButton>} below={<><div className="compact-scroll-tabs"><button className={tab==='production'?'active':''} onClick={()=>setTab('production')}><Milk size={17}/>Producción</button><button className={tab==='lactations'?'active':''} onClick={()=>setTab('lactations')}><CalendarRange size={17}/>Lactancias</button></div>{filtersOpen?<div className="compact-advanced-filter production-filters"><Field label="Animal"><ProductionAnimalFilter value={animalFilter} options={animalOptions.map(([id,label])=>({id,label}))} onChange={setAnimalFilter}/></Field><Field label="Desde"><Input type="date" value={fromDate} onChange={(event)=>setFromDate(event.target.value)}/></Field><Field label="Hasta"><Input type="date" value={toDate} onChange={(event)=>setToDate(event.target.value)}/></Field><Field label="Registro diario"><Input type="date" value={date} onChange={(event)=>setDate(event.target.value)}/></Field></div>:null}</>}/>
  {tab==='production'?<><ProductionChart series={chartSeries} xMode={animalFilter?'days':'date'} tankByDate={tankByDate} onDateSelect={setDate} filterOptions={animalOptions.map(([id,label])=>({id,label}))} filterValue={animalFilter} onFilterChange={setAnimalFilter}/>{animalFilter?<AnimalProductionHistory loading={productions.isLoading||lactations.isLoading} error={(productions.error??lactations.error) as Error|null} retry={()=>{void productions.refetch();void lactations.refetch();}} groups={animalProductionGroups} animalPhotos={directory.byId} canEdit={hasPermission('PRODUCCION_ADMINISTRAR')} editMilk={editMilk} remove={setDeleteItem} onOpen={(item)=>{const next=new URLSearchParams(searchParams);next.set('registro',String(item.id_produccion));setSearchParams(next);}}/>:<ProductionDaily loading={productions.isLoading||tanks.isLoading} error={(productions.error??tanks.error) as Error|null} retry={()=>{void productions.refetch();void tanks.refetch();}} rows={visibleProduction} tanks={visibleTanks} animalPhotos={directory.byId} canEdit={hasPermission('PRODUCCION_ADMINISTRAR')} editMilk={editMilk} editTank={editTank} remove={setDeleteItem} onOpen={(item)=>{const next=new URLSearchParams(searchParams);next.set('registro',String(item.id_produccion));setSearchParams(next);}}/>}</>:lactations.isLoading?<LoadingState/>:lactations.isError?<ErrorState message={(lactations.error as Error).message} onRetry={()=>void lactations.refetch()}/>:lactations.data?.length?<LactationList rows={lactations.data} animalPhotos={directory.byId} canEdit={hasPermission('LACTANCIA_ADMINISTRAR')} onOpen={(item)=>{const next=new URLSearchParams(searchParams);next.set('lactancia',String(item.id_lactancia));setSearchParams(next);}} onEdit={editLactation} onDelete={(item)=>setDeleteItem({module:'lactancias',id:String(item.id_lactancia)})}/>:<EmptyState icon={CalendarRange} title="Sin lactancias" description="Abre una lactancia para habilitar el registro diario de esa vaca."/>}
  <FloatingActionDock><IconButton label="Medidor" className="secondary-fab" onClick={()=>navigate('/produccion/medidor')}><Gauge size={21}/></IconButton>{tab==='production'&&hasPermission('PRODUCCION_ADMINISTRAR')?<IconButton label="Medición del tanque" className="secondary-fab" onClick={()=>{setTank(emptyTank(date));setTankOpen(true);}}><Milk size={21}/></IconButton>:null}{hasPermission(tab==='lactations'?'LACTANCIA_ADMINISTRAR':'PRODUCCION_ADMINISTRAR')?<IconButton label={tab==='lactations'?'Nueva lactancia':'Producción por vaca'} onClick={()=>tab==='lactations'?(setLactation(emptyLactation()),setLactationOpen(true)):(setMilk(emptyMilk(date)),setMilkOpen(true))}><Plus size={23}/></IconButton>:null}</FloatingActionDock>
  {lactationOpen?<LactationModal form={lactation} setForm={setLactation} females={females.data??[]} births={births.data??[]} animalPhotos={directory.byId} cowsLoading={females.isLoading} birthsLoading={births.isLoading} close={()=>setLactationOpen(false)} save={()=>saveLactation.mutate()} loading={saveLactation.isPending}/>:null}
  {milkOpen?<Modal title={milk.id_produccion?'Editar producción':'Producción por vaca'} onClose={()=>setMilkOpen(false)} footer={<><Button variant="ghost" onClick={()=>setMilkOpen(false)}>Cancelar</Button><Button onClick={()=>saveMilk.mutate()} loading={saveMilk.isPending}>Guardar</Button></>}><div className="form-stack"><Field label="Fecha" required><Input type="date" value={milk.fecha_produccion} onChange={(event)=>setMilk({...milk,fecha_produccion:event.target.value,id_vaca:''})}/></Field><Field label="Turno"><Select value={milk.turno} onChange={(event)=>setMilk({...milk,turno:event.target.value,id_vaca:''})}>{turns.map((turn)=><option key={turn} value={turn}>{humanizeCode(turn)}</option>)}</Select></Field><Field label="Vaca en ordeño" required hint="Solo aparecen las vacas que todavía no tienen producción en esta fecha y turno."><AnimalSelect value={milk.id_vaca} disabled={activeCows.isPending&&!selectableCows.length} options={selectableCows.map((cow)=>({id:cow.id_animal,name:cow.nombre,subtitle:cow.codigo_arete?`Arete ${cow.codigo_arete}`:null,photoUrl:directory.byId.get(cow.id_animal)?.foto_perfil}))} onChange={(id)=>setMilk({...milk,id_vaca:id})}/>{activeCows.isPending&&!selectableCows.length?<small className="muted">Consultando vacas disponibles…</small>:null}{activeCows.isError&&!selectableCows.length?<small className="field-error">No se pudieron consultar las vacas. Comprueba la conexión o los datos descargados.</small>:null}{!activeCows.isPending&&!activeCows.isError&&!selectableCows.length?<small className="muted">Todas las vacas disponibles ya tienen producción registrada en este turno.</small>:null}</Field><Field label="Litros" required><Input type="number" min="0" step="0.001" value={milk.litros} onChange={(event)=>setMilk({...milk,litros:event.target.value})}/></Field><Field label="Observaciones"><Textarea value={milk.observaciones} onChange={(event)=>setMilk({...milk,observaciones:event.target.value})}/></Field></div></Modal>:null}
  {tankOpen?<Modal title={tank.id_produccion_tanque?'Editar medición del tanque':'Total en tanque'} onClose={()=>setTankOpen(false)} footer={<><Button variant="ghost" onClick={()=>setTankOpen(false)}>Cancelar</Button><Button onClick={()=>saveTank.mutate()} loading={saveTank.isPending}>Guardar</Button></>}><div className="form-stack"><Field label="Fecha" required><Input type="date" value={tank.fecha_produccion} onChange={(event)=>setTank({...tank,fecha_produccion:event.target.value})}/></Field><Field label="Turno"><Select value={tank.turno} onChange={(event)=>setTank({...tank,turno:event.target.value})}>{turns.map((turn)=><option key={turn} value={turn}>{humanizeCode(turn)}</option>)}</Select></Field><Field label="Litros en tanque" required><Input type="number" min="0" step="0.001" value={tank.litros} onChange={(event)=>setTank({...tank,litros:event.target.value})}/></Field><Field label="Observaciones"><Textarea value={tank.observaciones} onChange={(event)=>setTank({...tank,observaciones:event.target.value})}/></Field></div></Modal>:null}
  {detailProduction?<Modal title="Detalle de producción" onClose={()=>{const next=new URLSearchParams(searchParams);next.delete('registro');setSearchParams(next);}} footer={<Button variant="ghost" onClick={()=>{const next=new URLSearchParams(searchParams);next.delete('registro');setSearchParams(next);}}>Cerrar</Button>}><div className="detail-grid"><div><small>Animal</small><strong>{String(detailProduction.animal??'—')}</strong></div><div><small>Fecha</small><strong>{formatDate(String(detailProduction.fecha_produccion))}</strong></div><div><small>Producción</small><strong>{formatNumber(detailProduction.litros as number|string,3)} L</strong></div><div><small>Turno</small><strong>{humanizeCode(String(detailProduction.turno??'UNICO'))}</strong></div><div><small>Fuente</small><strong>{humanizeCode(String(detailProduction.fuente??'MANUAL'))}</strong></div>{detailProduction.observaciones?<div><small>Observaciones</small><strong>{String(detailProduction.observaciones)}</strong></div>:null}</div></Modal>:null}
  {detailTank?<Modal title="Detalle de producción del tanque" onClose={()=>closeDetailParam('tanque')} footer={<Button variant="ghost" onClick={()=>closeDetailParam('tanque')}>Cerrar</Button>}><div className="detail-grid"><div><small>Fecha</small><strong>{formatDate(detailTank.fecha_produccion)}</strong></div><div><small>Producción</small><strong>{formatNumber(detailTank.litros,3)} L</strong></div><div><small>Turno</small><strong>{humanizeCode(detailTank.turno)}</strong></div><div><small>Fuente</small><strong>{humanizeCode(detailTank.fuente)}</strong></div>{detailTank.observaciones?<div><small>Observaciones</small><strong>{detailTank.observaciones}</strong></div>:null}</div></Modal>:null}
  {detailLactation?<Modal title="Detalle de lactancia" onClose={()=>closeDetailParam('lactancia')} footer={<Button variant="ghost" onClick={()=>closeDetailParam('lactancia')}>Cerrar</Button>}><div className="detail-grid"><div><small>Animal</small><strong>{String(detailLactation.animal??detailLactation.vaca??detailLactation.nombre??'—')}</strong></div><div><small>Inicio</small><strong>{formatDate(String(detailLactation.fecha_inicio))}</strong></div><div><small>Fin</small><strong>{formatDate(detailLactation.fecha_fin?String(detailLactation.fecha_fin):null)}</strong></div><div><small>Estado</small><strong>{detailLactation.activa?'Activa':'Cerrada'}</strong></div><div><small>En ordeño</small><strong>{detailLactation.en_ordeno?'Sí':'No'}</strong></div>{detailLactation.observaciones?<div><small>Observaciones</small><strong>{String(detailLactation.observaciones)}</strong></div>:null}</div></Modal>:null}
  {deleteItem?<ConfirmDialog title="Eliminar registro" message="El registro dejará de contabilizarse en los totales." onClose={()=>setDeleteItem(null)} onConfirm={()=>remove.mutate()} loading={remove.isPending}/>:null}</div>;
}

function LactationList({rows,animalPhotos,canEdit,onOpen,onEdit,onDelete}:{rows:GenericRecord[];animalPhotos:ReadonlyMap<string,{nombre?:string;codigo_arete?:string|null;foto_perfil?:string|null}>;canEdit:boolean;onOpen:(item:GenericRecord)=>void;onEdit:(item:GenericRecord)=>void;onDelete:(item:GenericRecord)=>void}){
  return <Card className="lactation-compact-list">{rows.map((item)=>{const animal=animalPhotos.get(String(item.id_vaca));const name=String(item.animal??item.vaca??animal?.nombre??'Animal sin nombre');const tag=item.codigo_arete??animal?.codigo_arete;return <button type="button" className="lactation-compact-row" key={String(item.id_lactancia)} onClick={()=>onOpen(item)}><AnimalIdentity option={{id:String(item.id_vaca),name,photoUrl:animal?.foto_perfil,subtitle:tag?`Arete ${tag}`:'Sin arete'}}/><span className="lactation-period"><small>Período</small><strong>{formatDate(String(item.fecha_inicio))} – {item.fecha_fin?formatDate(String(item.fecha_fin)):'Actualidad'}</strong></span><span className="lactation-status"><Badge tone={item.activa?'success':'neutral'}>{item.activa?'Activa':'Cerrada'}</Badge>{item.en_ordeno?<Badge tone="info">En ordeño</Badge>:null}</span>{canEdit?<span className="production-compact-actions" onClick={(event)=>event.stopPropagation()}><IconButton label="Editar lactancia" onClick={()=>onEdit(item)}><Edit3 size={16}/></IconButton><IconButton label="Eliminar lactancia" onClick={()=>onDelete(item)}><Trash2 size={16}/></IconButton></span>:null}</button>;})}</Card>;
}

function AnimalProductionHistory({loading,error,retry,groups,animalPhotos,canEdit,editMilk,remove,onOpen}:{loading:boolean;error:Error|null;retry:()=>void;groups:AnimalProductionGroup[];animalPhotos:ReadonlyMap<string,{foto_perfil?:string|null}>;canEdit:boolean;editMilk:(item:GenericRecord)=>void;remove:(item:{module:string;id:string})=>void;onOpen:(item:GenericRecord)=>void}){
  if(loading)return <LoadingState/>;
  if(error)return <ErrorState message={error.message} onRetry={retry}/>;
  if(!groups.length)return <EmptyState icon={Milk} title="Sin producción para este animal" description="No hay registros dentro del período seleccionado."/>;
  return <section className="animal-production-history">
    <div className="production-lactation-totals" aria-label="Totales de producción por parto">{groups.map((group)=><div key={group.id}><CalendarRange size={17}/><span><small>{group.label}</small><strong>{formatNumber(group.total,3)} L</strong></span></div>)}</div>
    {groups.map((group)=><div className="production-daily-group production-lactation-group" key={group.id}>
      <header><span><Milk size={18}/><span><strong>{group.label}</strong><small>{group.rows.length} {group.rows.length===1?'registro':'registros'}</small></span></span></header>
      <div className="production-compact-list">{group.rows.map((item)=>{const productionDate=dateInputValue(String(item.fecha_produccion));const day=Math.max(0,Math.round((Date.parse(productionDate)-Date.parse(group.start))/86400000));return <button type="button" className="production-compact-row production-row-with-photo" key={String(item.id_produccion)} onClick={()=>onOpen(item)}><AnimalIdentity option={{id:String(item.id_vaca??''),name:formatDate(String(item.fecha_produccion)),photoUrl:animalPhotos.get(String(item.id_vaca??''))?.foto_perfil,subtitle:`Día ${day} · ${humanizeCode(String(item.turno??'UNICO'))} · ${humanizeCode(String(item.fuente??'MANUAL'))}`}}/><b>{formatNumber(item.litros as number|string,3)} L</b>{canEdit?<span className="production-compact-actions" onClick={(event)=>event.stopPropagation()}><IconButton label="Editar" onClick={()=>editMilk(item)}><Edit3 size={15}/></IconButton><IconButton label="Eliminar" onClick={()=>remove({module:'producciones',id:String(item.id_produccion)})}><Trash2 size={15}/></IconButton></span>:null}</button>;})}</div>
    </div>)}
  </section>;
}

function ProductionDaily({loading,error,retry,rows,tanks,animalPhotos,canEdit,editMilk,editTank,remove,onOpen}:{loading:boolean;error:Error|null;retry:()=>void;rows:GenericRecord[];tanks:TankProduction[];animalPhotos:ReadonlyMap<string,{foto_perfil?:string|null}>;canEdit:boolean;editMilk:(item:GenericRecord)=>void;editTank:(item:TankProduction)=>void;remove:(item:{module:string;id:string})=>void;onOpen:(item:GenericRecord)=>void}){
  if(loading)return <LoadingState/>;
  if(error)return <ErrorState message={error.message} onRetry={retry}/>;
  const animalTotal=rows.reduce((sum,item)=>sum+Number(item.litros??0),0);
  const tankTotal=tanks.reduce((sum,item)=>sum+Number(item.litros??0),0);
  return <section className="production-daily-compact">
    <div className="production-daily-group">
      <header><span><Milk size={18}/><strong>Producción por animal</strong></span><b>{formatNumber(animalTotal,3)} L</b></header>
      {rows.length?<div className="production-compact-list">{rows.map((item)=><button type="button" className="production-compact-row production-row-with-photo" key={String(item.id_produccion)} onClick={()=>onOpen(item)}><AnimalIdentity option={{id:String(item.id_vaca??''),name:String(item.animal),photoUrl:animalPhotos.get(String(item.id_vaca??''))?.foto_perfil,subtitle:`${humanizeCode(String(item.turno??'UNICO'))} · ${humanizeCode(String(item.fuente??'MANUAL'))}`}}/><b>{formatNumber(item.litros as number|string,3)} L</b>{canEdit?<span className="production-compact-actions" onClick={(event)=>event.stopPropagation()}><IconButton label="Editar" onClick={()=>editMilk(item)}><Edit3 size={15}/></IconButton><IconButton label="Eliminar" onClick={()=>remove({module:'producciones',id:String(item.id_produccion)})}><Trash2 size={15}/></IconButton></span>:null}</button>)}</div>:<p className="production-compact-empty">Sin producción animal en la fecha seleccionada.</p>}
    </div>
    <div className="production-daily-group tank-group">
      <header><span><Gauge size={18}/><strong>Producción del tanque</strong></span><b>{formatNumber(tankTotal,3)} L</b></header>
      {tanks.length?<div className="production-compact-list">{tanks.map((item)=><div className="production-compact-row" key={item.id_produccion_tanque}><span><strong>{humanizeCode(item.turno)}</strong><small>{humanizeCode(item.fuente??'MANUAL')}{item.observaciones?` · ${item.observaciones}`:''}</small></span><b>{formatNumber(item.litros,3)} L</b>{canEdit?<span className="production-compact-actions"><IconButton label="Editar" onClick={()=>editTank(item)}><Edit3 size={15}/></IconButton><IconButton label="Eliminar" onClick={()=>remove({module:'produccion-tanque',id:item.id_produccion_tanque})}><Trash2 size={15}/></IconButton></span>:null}</div>)}</div>:<p className="production-compact-empty">Sin medición de tanque en la fecha seleccionada.</p>}
    </div>
  </section>;
}

function LactationModal({form,setForm,females,births,animalPhotos,cowsLoading,birthsLoading,close,save,loading}:{form:LactationForm;setForm:(form:LactationForm)=>void;females:LactationCowOption[];births:LactationBirthOption[];animalPhotos:ReadonlyMap<string,{foto_perfil?:string|null}>;cowsLoading:boolean;birthsLoading:boolean;close:()=>void;save:()=>void;loading:boolean}){
  const availableBirths=births.filter((birth)=>!birth.ya_relacionado||birth.id_parto===form.id_parto);
  const selectedBirth=births.find((item)=>item.id_parto===form.id_parto);
  return <Modal title={form.id_lactancia?'Editar lactancia':'Nueva lactancia'} onClose={close} footer={<><Button variant="ghost" onClick={close}>Cancelar</Button><Button onClick={save} loading={loading}>Guardar</Button></>}><div className="form-stack"><Field label="Vaca con parto registrado" required><AnimalSelect value={form.id_vaca} disabled={cowsLoading} options={females.map((animal)=>({id:animal.id_animal,name:animal.nombre,subtitle:animal.codigo_arete?`Arete ${animal.codigo_arete}`:null,photoUrl:animalPhotos.get(animal.id_animal)?.foto_perfil}))} onChange={(id)=>setForm({...form,id_vaca:id,id_parto:''})}/>{!cowsLoading&&!females.length?<small className="muted">No hay vacas con parto registrado que estén libres de otra lactancia activa.</small>:null}</Field><Field label="Parto relacionado" required hint="La lactancia comenzará automáticamente en la fecha de este parto."><Select value={form.id_parto} disabled={!form.id_vaca||birthsLoading} onChange={(event)=>setForm({...form,id_parto:event.target.value})}><option value="">{!form.id_vaca?'Selecciona primero una vaca':birthsLoading?'Cargando partos…':'Selecciona un parto'}</option>{availableBirths.map((birth)=><option key={birth.id_parto} value={birth.id_parto}>{formatDate(birth.fecha_parto)} · {birth.total_crias} cría(s)</option>)}</Select>{form.id_vaca&&!birthsLoading&&!availableBirths.length?<small className="muted">Esta vaca no tiene partos disponibles para relacionar.</small>:null}</Field>{selectedBirth?<div className="form-alert"><strong>Inicio automático:</strong> {formatDate(selectedBirth.fecha_parto)}</div>:null}<label className="checkbox"><input type="checkbox" checked={form.activa} onChange={(event)=>setForm({...form,activa:event.target.checked,en_ordeno:event.target.checked?form.en_ordeno:false,fecha_fin:event.target.checked?'':form.fecha_fin})}/>Lactancia activa</label>{form.activa?<label className="checkbox"><input type="checkbox" checked={form.en_ordeno} onChange={(event)=>setForm({...form,en_ordeno:event.target.checked})}/>En ordeño</label>:<Field label="Fin" required><Input type="date" min={selectedBirth?dateInputValue(selectedBirth.fecha_parto):undefined} value={form.fecha_fin} onChange={(event)=>setForm({...form,fecha_fin:event.target.value})}/></Field>}<small className="muted">Solo las vacas marcadas “En ordeño” estarán disponibles al registrar producción diaria.</small><Field label="Observaciones"><Textarea value={form.observaciones} onChange={(event)=>setForm({...form,observaciones:event.target.value})}/></Field></div></Modal>;
}
