import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity as ActivityIcon, ChevronRight, Edit3, ImagePlus, Plus, Trash2 } from 'lucide-react';
import { apiRequest, ApiError } from '../../api/client';
import { useAuth } from '../../auth/AuthContext';
import { AnimalMultiPicker } from '../../components/AnimalMultiPicker';
import { useToast } from '../../components/ToastContext';
import { Badge, Button, Card, ConfirmDialog, EmptyState, ErrorState, Field, Input, ListToolbar, LoadingState, Modal, PageHeader, Select, Textarea } from '../../components/ui';
import { itemId, itemLabel, useCatalog } from '../../hooks/useCatalog';
import { useListControls } from '../../hooks/useListControls';
import type { Activity, RecordImage } from '../../types/api';
import { currentDateInput, dateInputValue, formatDate } from '../../utils';

interface ActivityForm{id_tipo_actividad:string;fecha:string;descripcion:string;id_animales:string[]}
const emptyForm=():ActivityForm=>({id_tipo_actividad:'',fecha:currentDateInput(),descripcion:'',id_animales:[]});

export function ActivitiesPage(){
  const {hasPermission}=useAuth();const toast=useToast();const client=useQueryClient();
  const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Activity|null>(null);const [selected,setSelected]=useState<Activity|null>(null);const [deleting,setDeleting]=useState<Activity|null>(null);const [form,setForm]=useState<ActivityForm>(emptyForm);const [files,setFiles]=useState<File[]>([]);
  const query=useQuery({queryKey:['activities'],queryFn:()=>apiRequest<Activity[]>('/actividades')});const types=useCatalog('tipos-actividad');
  const list=useListControls({items:query.data??[],storageKey:'activities',searchText:(item)=>`${item.tipo_actividad} ${item.descripcion??''} ${item.animales.map((animal)=>`${animal.nombre} ${animal.codigo_arete??''}`).join(' ')}`,dateValue:(item)=>item.fecha,nameValue:(item)=>item.tipo_actividad});
  const save=useMutation({mutationFn:async()=>{if(!form.id_tipo_actividad||!form.fecha||!form.id_animales.length)throw new Error('Selecciona el tipo, la fecha y al menos un animal.');const activity=await apiRequest<Activity>(editing?`/actividades/${editing.id_actividad}`:'/actividades',{method:editing?'PATCH':'POST',body:{...form,descripcion:form.descripcion.trim()||null}});const id=editing?.id_actividad??activity.id_actividad;if(files.length){const data=new FormData();files.forEach((file)=>data.append('imagenes',file));await apiRequest(`/actividades/${id}/imagenes`,{method:'POST',body:data});}return activity;},onSuccess:()=>{toast.show(editing?'Actividad actualizada.':'Actividad registrada.');setOpen(false);setEditing(null);setForm(emptyForm());setFiles([]);void client.invalidateQueries({queryKey:['activities']});},onError:(error)=>toast.show(error instanceof ApiError?error.message:(error as Error).message,'error')});
  const remove=useMutation({mutationFn:()=>apiRequest(`/actividades/${deleting?.id_actividad}`,{method:'DELETE'}),onSuccess:()=>{toast.show('Actividad eliminada.');setDeleting(null);void client.invalidateQueries({queryKey:['activities']});},onError:(error)=>toast.show((error as ApiError).message,'error')});
  const deletePhoto=useMutation({mutationFn:(image:RecordImage)=>apiRequest(`/actividades/imagenes/${image.id_actividad_imagen}`,{method:'DELETE'}),onSuccess:(_,image)=>{setEditing((current)=>current?{...current,imagenes:current.imagenes.filter((item)=>item.id_actividad_imagen!==image.id_actividad_imagen)}:current);toast.show('Fotografía eliminada.');void client.invalidateQueries({queryKey:['activities']});},onError:(error)=>toast.show((error as ApiError).message,'error')});
  const edit=(item:Activity)=>{setForm({id_tipo_actividad:item.id_tipo_actividad,fecha:dateInputValue(item.fecha),descripcion:item.descripcion??'',id_animales:item.animales.map((animal)=>animal.id_animal)});setFiles([]);setEditing(item);setSelected(null);setOpen(true);};
  return <div><PageHeader title="Otras actividades" description="Registra descornes, herrajes y otras labores realizadas sobre uno o varios animales." action={hasPermission('ACTIVIDAD_ADMINISTRAR')?<Button onClick={()=>{setEditing(null);setForm(emptyForm());setFiles([]);setOpen(true);}}><Plus size={18}/>Nueva actividad</Button>:undefined}/><ListToolbar search={list.search} onSearch={list.setSearch} order={list.order} onOrder={list.setOrder} placeholder="Buscar actividad, animal o arete…" count={list.visible.length}/>
  {query.isLoading?<LoadingState/>:query.isError?<ErrorState message={(query.error as Error).message} onRetry={()=>void query.refetch()}/>:list.visible.length?<Card className="record-list"><div className="record-list-head"><span>Actividad</span><span>Fecha</span><span>Animales</span><span>Fotos</span><span/><span/></div>{list.visible.map((item)=><button type="button" className="record-list-row" key={item.id_actividad} onClick={()=>setSelected(item)}><span><strong>{item.tipo_actividad}</strong><small>{item.descripcion||'Sin descripción'}</small></span><span><strong>{formatDate(item.fecha)}</strong></span><span><strong>{item.animales.length}</strong><small>{item.animales.slice(0,2).map((animal)=>animal.nombre).join(', ')}</small></span><span><Badge tone={item.imagenes.length?'success':'neutral'}>{item.imagenes.length} fotos</Badge></span><span/><span className="record-row-actions">{hasPermission('ACTIVIDAD_ADMINISTRAR')?<Button variant="ghost" onClick={(event)=>{event.stopPropagation();edit(item);}}><Edit3 size={16}/>Editar</Button>:null}<ChevronRight size={18}/></span></button>)}</Card>:<EmptyState icon={ActivityIcon} title="Sin actividades" description="Registra la primera actividad realizada sobre los animales."/>}
  {selected?<Modal title="Detalle de la actividad" wide onClose={()=>setSelected(null)} footer={<><Button variant="ghost" onClick={()=>setSelected(null)}>Cerrar</Button>{hasPermission('ACTIVIDAD_ADMINISTRAR')?<><Button variant="secondary" onClick={()=>edit(selected)}><Edit3 size={16}/>Editar</Button><Button variant="ghost" onClick={()=>setDeleting(selected)}><Trash2 size={16}/>Eliminar</Button></>:null}</>}><div className="record-detail"><div className="record-detail-heading"><div className="record-icon"><ActivityIcon size={22}/></div><div><h2>{selected.tipo_actividad}</h2><p>{formatDate(selected.fecha)}</p></div></div><section><h3>Animales</h3><div className="detail-lines compact">{selected.animales.map((animal)=><div key={animal.id_animal}><span><strong>{animal.nombre}</strong><small>{animal.codigo_arete?`Arete ${animal.codigo_arete}`:'Sin arete'}</small></span></div>)}</div></section>{selected.imagenes.length?<section><h3>Fotografías</h3><div className="record-photo-grid">{selected.imagenes.map((image)=><a href={image.secure_url} target="_blank" rel="noreferrer" key={image.id_actividad_imagen}><img src={image.secure_url} alt="Actividad"/></a>)}</div></section>:null}{selected.descripcion?<section><h3>Descripción</h3><p>{selected.descripcion}</p></section>:null}</div></Modal>:null}
  {open?<Modal title={editing?'Editar actividad':'Nueva actividad'} wide onClose={()=>setOpen(false)} footer={<><Button variant="ghost" onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={()=>save.mutate()} loading={save.isPending}>Guardar</Button></>}><div className="form-stack"><div className="form-grid"><Field label="Tipo de actividad" required><Select value={form.id_tipo_actividad} onChange={(event)=>setForm({...form,id_tipo_actividad:event.target.value})}><option value="">Selecciona</option>{types.data?.filter((item)=>item.activo!==false).map((item)=><option key={itemId(item)} value={itemId(item)}>{itemLabel(item)}</option>)}</Select></Field><Field label="Fecha" required><Input type="date" value={form.fecha} onChange={(event)=>setForm({...form,fecha:event.target.value})}/></Field></div><Field label="Animales" required><AnimalMultiPicker value={form.id_animales} onChange={(ids)=>setForm({...form,id_animales:ids})}/></Field><Field label="Descripción"><Textarea value={form.descripcion} onChange={(event)=>setForm({...form,descripcion:event.target.value})}/></Field><ActivityPhotoPicker existing={editing?.imagenes??[]} files={files} onFiles={setFiles} onDelete={(image)=>deletePhoto.mutate(image)}/></div></Modal>:null}
  {deleting?<ConfirmDialog title="Eliminar actividad" message="Se conservarán los animales; solo se eliminará este registro y sus relaciones." onClose={()=>setDeleting(null)} onConfirm={()=>remove.mutate()} loading={remove.isPending}/>:null}</div>;
}

function ActivityPhotoPicker({existing,files,onFiles,onDelete}:{existing:RecordImage[];files:File[];onFiles:(files:File[])=>void;onDelete:(image:RecordImage)=>void}){const capacity=Math.max(0,3-existing.length);return <Field label="Fotografías" hint="Hasta tres."><div className="record-photo-picker"><div className="record-photo-grid">{existing.map((image)=><div key={image.id_actividad_imagen}><img src={image.secure_url} alt=""/><button type="button" onClick={()=>onDelete(image)}><Trash2 size={14}/></button></div>)}{files.map((file,index)=><div key={`${file.name}-${index}`}><ActivityFilePreview file={file}/><button type="button" onClick={()=>onFiles(files.filter((_,position)=>position!==index))}><Trash2 size={14}/></button></div>)}</div><label className={`photo-upload-button ${files.length>=capacity?'disabled':''}`}><ImagePlus size={18}/>Agregar fotografías<input hidden type="file" accept="image/*" multiple disabled={files.length>=capacity} onChange={(event)=>{onFiles([...files,...Array.from(event.target.files??[])].slice(0,capacity));event.currentTarget.value='';}}/></label><small>{existing.length+files.length} de 3</small></div></Field>;}
function ActivityFilePreview({file}:{file:File}){const [url,setUrl]=useState('');useEffect(()=>{const next=URL.createObjectURL(file);setUrl(next);return()=>URL.revokeObjectURL(next);},[file]);return <img src={url} alt={file.name}/>;}
