import { useEffect, useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Edit3, MapPin, Plus, Trash2 } from 'lucide-react';
import { apiRequest, ApiError } from '../../api/client';
import { useAuth } from '../../auth/AuthContext';
import { useToast } from '../../components/ToastContext';
import { Badge, Button, Card, ConfirmDialog, EmptyState, ErrorState, Field, Input, LoadingState, Modal, PageHeader, Select, Textarea } from '../../components/ui';
import type { Location } from '../../types/api';
import { nullIfEmpty, numberOrNull } from '../../utils';

interface LocationForm { codigo: string; nombre: string; tipo: Location['tipo']; descripcion: string; latitud: string; longitud: string; activo: boolean }
const empty: LocationForm = { codigo: '', nombre: '', tipo: 'OTRO', descripcion: '', latitud: '', longitud: '', activo: true };

function LocationModal({ location, onClose }: { location?: Location | null; onClose: () => void }) {
  const client = useQueryClient(); const toast = useToast(); const [form, setForm] = useState<LocationForm>(empty);
  useEffect(() => setForm(location ? { codigo: location.codigo ?? '', nombre: location.nombre, tipo: location.tipo, descripcion: location.descripcion ?? '', latitud: location.latitud?.toString() ?? '', longitud: location.longitud?.toString() ?? '', activo: location.activo } : empty), [location]);
  const mutation = useMutation({ mutationFn: () => apiRequest(location ? `/ubicaciones/${location.id_ubicacion}` : '/ubicaciones', { method: location ? 'PATCH' : 'POST', body: { codigo: nullIfEmpty(form.codigo), nombre: form.nombre, tipo: form.tipo, descripcion: nullIfEmpty(form.descripcion), latitud: numberOrNull(form.latitud), longitud: numberOrNull(form.longitud), activo: form.activo } }), onSuccess: async () => { toast.show(location ? 'Ubicación actualizada.' : 'Ubicación creada.'); await client.invalidateQueries({ queryKey: ['locations'] }); onClose(); }, onError: (error) => toast.show((error as ApiError).message, 'error') });
  return <Modal title={location ? 'Editar ubicación' : 'Nueva ubicación'} onClose={onClose} footer={<><Button variant="ghost" onClick={onClose}>Cancelar</Button><Button type="submit" form="location-form" loading={mutation.isPending}>Guardar</Button></>}><form id="location-form" className="form-stack" onSubmit={(event: FormEvent) => { event.preventDefault(); mutation.mutate(); }}><div className="form-grid"><Field label="Nombre" required><Input value={form.nombre} onChange={(e) => setForm((x) => ({ ...x, nombre: e.target.value }))} required /></Field><Field label="Código"><Input value={form.codigo} onChange={(e) => setForm((x) => ({ ...x, codigo: e.target.value }))} /></Field><Field label="Tipo" hint={location ? "Los potreros y corrales se editan en sus módulos especializados." : "Las nuevas ubicaciones generales se registran como Otro."} required><Select value={form.tipo} disabled><option value="OTRO">Otro</option><option value="POTRERO">Potrero</option><option value="CORRAL">Corral</option></Select></Field><Field label="Estado"><Select value={String(form.activo)} onChange={(e) => setForm((x) => ({ ...x, activo: e.target.value === 'true' }))}><option value="true">Activo</option><option value="false">Inactivo</option></Select></Field><Field label="Latitud"><Input type="number" step="any" value={form.latitud} onChange={(e) => setForm((x) => ({ ...x, latitud: e.target.value }))} /></Field><Field label="Longitud"><Input type="number" step="any" value={form.longitud} onChange={(e) => setForm((x) => ({ ...x, longitud: e.target.value }))} /></Field></div><Field label="Descripción"><Textarea rows={3} value={form.descripcion} onChange={(e) => setForm((x) => ({ ...x, descripcion: e.target.value }))} /></Field></form></Modal>;
}

export function LocationsPage() {
  const { hasPermission } = useAuth(); const toast = useToast(); const client = useQueryClient();
  const [editing, setEditing] = useState<Location | null | undefined>(undefined); const [deleting, setDeleting] = useState<Location | null>(null); const [type, setType] = useState('');
  const query = useQuery({ queryKey: ['locations', type], queryFn: () => apiRequest<Location[]>(`/ubicaciones${type ? `?tipo=${type}` : ''}`) });
  const remove = useMutation({ mutationFn: (id: string) => apiRequest(`/ubicaciones/${id}`, { method: 'DELETE' }), onSuccess: async () => { toast.show('Ubicación eliminada.'); setDeleting(null); await client.invalidateQueries({ queryKey: ['locations'] }); }, onError: (error) => toast.show((error as ApiError).message, 'error') });
  return <div><PageHeader title="Ubicaciones" description="Lugares físicos donde pueden encontrarse los animales." action={hasPermission('UBICACION_ADMINISTRAR') ? <Button onClick={() => setEditing(null)}><Plus size={18} />Otra ubicación</Button> : undefined} /><div className="toolbar"><Select value={type} onChange={(e) => setType(e.target.value)}><option value="">Todos los tipos</option><option value="POTRERO">Potreros</option><option value="CORRAL">Corrales</option><option value="OTRO">Otros</option></Select></div>{query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message={(query.error as Error).message} onRetry={() => void query.refetch()} /> : query.data?.length === 0 ? <EmptyState icon={MapPin} title="Sin ubicaciones" description="Crea potreros, corrales u otros lugares de la propiedad." /> : <div className="record-grid">{query.data?.map((location) => <Card key={location.id_ubicacion} className="record-card"><div className="record-card-header"><div className="record-icon"><MapPin size={22} /></div><div><h3>{location.nombre}</h3><span>{location.codigo || 'Sin código'}</span></div><Badge tone={location.activo ? 'success' : 'neutral'}>{location.tipo}</Badge></div><div className="record-details"><span><small>Animales actuales</small><strong>{location.total_animales}</strong></span><span><small>Coordenadas</small><strong>{location.latitud != null && location.longitud != null ? `${location.latitud}, ${location.longitud}` : 'Sin registrar'}</strong></span></div><p>{location.descripcion || 'Sin descripción.'}</p>{hasPermission('UBICACION_ADMINISTRAR') && location.tipo === 'OTRO' ? <div className="record-actions"><Button variant="ghost" onClick={() => setEditing(location)}><Edit3 size={17} />Editar</Button><Button variant="ghost" onClick={() => setDeleting(location)}><Trash2 size={17} />Eliminar</Button></div> : null}</Card>)}</div>}{editing !== undefined ? <LocationModal location={editing} onClose={() => setEditing(undefined)} /> : null}{deleting ? <ConfirmDialog title="Eliminar ubicación" message={`¿Eliminar ${deleting.nombre}? No será posible si existen relaciones que lo impidan.`} onClose={() => setDeleting(null)} onConfirm={() => remove.mutate(deleting.id_ubicacion)} loading={remove.isPending} /> : null}</div>;
}
